---
abstract: 'Asynchronous MySQL queries'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-DBI-MySQL
provides:
  AnyEvent::DBI::MySQL:
    file: lib/AnyEvent/DBI/MySQL.pm
    version: v1.0.1
  AnyEvent::DBI::MySQL::db:
    file: lib/AnyEvent/DBI/MySQL.pm
    version: 0
  AnyEvent::DBI::MySQL::st:
    file: lib/AnyEvent/DBI/MySQL.pm
    version: 0
  AnyEvent::DBI::MySQL::st::ready:
    file: lib/AnyEvent/DBI/MySQL.pm
    version: 0
requires:
  AnyEvent: 0
  DBD::mysql: 0
  DBI: 0
  Scalar::Util: 0
  perl: v5.10.0
  version: 0.77
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v1.0.1
